version: '3'
services:
  dmteam-app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_PREFIX=${POSTGRES_DB_PREFIX}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "${POSTGRES_DB_PREFIX}_development"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
